name: ng_bootstrap
version: 1.0.0-alpha+2
description: Angular 2 and Bootstrap 4
authors:
  - Luis Vargas <luisvargastijerino@gmail.com>
  - Adao Jr. <itsjunnior@gmail.com>
  - Ismael Blasco <isdswii@gmail.com>
homepage: https://github.com/dart-league/ng_bootstrap
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  angular: 5.0.0-alpha+13
  node_shims: ^0.1.3
  intl: ^0.15.0
  bootstrap_sass: 4.1.0
#  bootstrap_sass:
#    path: ../bootstrap_sass
  stream_transform: ^0.0.11
  font_awesome: ^4.7.0
  dev_string_converter: ^0.1.0
  angular_forms: ^2.0.0-alpha+5
dev_dependencies:
  build_runner: ^0.8.9
  sass_builder: ^2.0.0
#  sass_builder:
#    path: ../sass_builder
