name: ng_bootstrap
version: 1.2.0-alpha.1
description: Angular 2 and Bootstrap 4
authors:
  - Luis Vargas <luisvargastijerino@gmail.com>
  - Adao Jr. <itsjunnior@gmail.com>
  - Ismael Blasco <isdswii@gmail.com>
homepage: https://github.com/dart-league/ng_bootstrap
environment:
  sdk: '>=2.1.0-dev <3.0.0'
dependencies:
  angular: ^6.0.0-alpha+1
#  angular:
#    path: ../angular/angular
  js_shims: ^1.0.0
  intl: ^0.15.0
  bootstrap_sass: ^4.3.1
#  bootstrap_sass:
#    path: ../bootstrap_sass
  stream_transform: ^0.0.11
  font_awesome: ^5.10.1
  angular_forms: ^2.0.0
#  angular_forms:
#    path: ../angular/angular_forms
dev_dependencies:
  build_runner: any
  sass_builder: ^2.1.1
#  sass_builder:
#    path: ../sass_builder
