name: ng_bootstrap
version: 0.8.5
description: Angular 2 and Bootstrap 4
authors:
  - Luis Vargas <luisvargastijerino@gmail.com>
  - Adao Jr. <itsjunnior@gmail.com>
  - Ismael Blasco <isdswii@gmail.com>
homepage: https://github.com/dart-league/ng_bootstrap
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  angular: ^4.0.0
  browser: ^0.10.0
  node_shims: ^0.1.3
  intl: ^0.15.0
  dart_to_js_script_rewriter: ^1.0.1
  bootstrap_sass: ^4.0.0-alpha.5+1
#  bootstrap_sass:
#    path: ../bootstrap_sass
  stream_transform: ^0.0.9
  font_awesome: ^4.6.3
  dev_string_converter: ^0.1.0
  angular_forms: ^1.0.0
dev_dependencies:
  build_runner: ^0.4.0
  sass_builder: ^0.2.0
#  sass_builder:
#    path: ../sass_builder
transformers:
- angular
- dart_to_js_script_rewriter
- $dart2js:
    $include: web/index.dart
